### ISSUE TITLE
CUDA out of memory under default config

### ISSUE THREAD

**Issue by Lechatelia** [facebookresearch/MaskFormer#11]
Hey, Dear authors
 I wanna reproduce this interesting work. However, I meet `CUDA out of memory` when using the default config files for coco stuff and coco panoptic.  (batchsize per gpu is 4 and 2 for coco stuff and panoptic respectively.)
  Our experiments encounter OOM every 10，000 iterations or even more. And we use 32g v100 too. So, i want to know if you use other codes or different environments.
below is my environment info

>`sys.platform            linux
Python                  3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
numpy                   1.21.1
detectron2              0.5 @/mnt/lustre/zhujinguo/anaconda3/envs/d2/lib/python3.7/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1+cu101 @/mnt/lustre/zhujinguo/anaconda3/envs/d2/lib/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0,1,2,3,4,5,6,7     Tesla V100-SXM2-32GB (arch=7.0)
CUDA_HOME               /mnt/lustre/share/cuda-10.1
Pillow                  8.3.1
torchvision             0.8.2+cu101 @/mnt/lustre/zhujinguo/anaconda3/envs/d2/lib/python3.7/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.5.post20210722
iopath                  0.1.8
cv2                     4.5.3`

Thank you!

**Comment by bowenc0221** [comment]
We train our model on COCO-stuff with 8 Tesla V100-SXM2-32GB GPUs (4 images per GPU) and on COCO-panoptic with 64 Tesla V100-SXM2-32GB GPUs (1 images per GPU).

You should not encounter OOM for COCO-stuff with your setting. But the OOM error for COCO-panoptic is expected (COCO images have different sizes, so you might get OOM after some iterations).

**Comment by Lechatelia** [comment]
OK, thanks for your help. 
I got the wrong gpu-number for coco panoptic. I will carry out our coco-stuff experiments again!
