### ISSUE TITLE
Training Log of maskformer_panoptic_swin_tiny_bs64_554k.yaml

### ISSUE THREAD

**Issue by MaureenZOU** [facebookresearch/MaskFormer#14]
Thanks for your great work. It would be really appreciated if you have any chance to share the training log of config maskformer_panoptic_swin_tiny_bs64_554k.yaml.

If there is no training log, could you please share your experience on when the network will achieve 50% final accuracy or any equivalent information?

Thanks in advance!

**Comment by bowenc0221** [comment]
All the training logs are available under the `metrics`. Unfortunately, most COCO panoptic evaluation numbers are not correct in these training logs and but the training losses are correct.

I have not checked intermediate performance myself so I'm also not sure when the network achieves 50% final accuracy as well.

**Comment by MaureenZOU** [comment]
Thanks a lot for your information. It is really helpful!
