### ISSUE TITLE
the mIoU in ade20k is not good like in the ade20k benchmark

### ISSUE THREAD

**Issue by daixiaolei623** [facebookresearch/MaskFormer#16]
thank you for your great work.
However, the mIoU i test with the maskformer_swin_large_IN21k_384_bs16_160k_res640.yaml and model is only 0.4022, 
but your mIoU in ade20k benchmark is 0.4967, which is much better.
Could you please tell me why?
thank you.

**Comment by daixiaolei623** [comment]
I used the model_final_45388b.pkl and maskformer_swin_large_IN21k_384_bs16_160k_res640.yaml

**Comment by bowenc0221** [comment]
We follow Swin Transformer setting to train our model in both train and val set, but that won't give you +9 mIoU difference. There might be something wrong when you save predictions.

**Comment by daixiaolei623** [comment]
@bowenc0221 
thank you.
i will not use this result to ade20k benchmark in public, and my mIoU is hidden in benchmark, so you don't have to worry about the leakage of this result.
 i just want to know how the maskfromer can get the 0.4967 mIoU in ade20k benchmark, because it is a great progress.
Do you mean that the model_final_45388b.pkl is not the best model? 
or There might be something wrong when you save predictions? but i did save the predictions (sem_seg in your code),Is this wrong?

**Comment by bowenc0221** [comment]
> Do you mean that the model_final_45388b.pkl is not the best model?

model_final_45388b.pkl is the best model trained on **train** set, and the model we used to evaluate on the ADE20K benchmark is trained on **train + val** set following Swin Transformer.

> but i did save the predictions (sem_seg in your code),Is this wrong?

You didn't use multi-scale inference.

**Comment by daixiaolei623** [comment]
@bowenc0221 
thank you.
i am a student of Jiangsu university about CS, i just want to learn this excellent model.
Could you please share the corresponding model and multi-scale inference to let me learn this.  i do not understand how to do this.
thank you.

**Comment by daixiaolei623** [comment]
@bowenc0221 
my email is asertu@126.com
