### ISSUE TITLE
config error?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/MaskFormer#2]
```
mask_former/config.py", line 79, in add_mask_former_config
    cfg.MODEL.SWIN.QK_SCALE = None
  File "/fvcore/fvcore/common/config.py", line 148, in __setattr__
    super().__setattr__(name, val)
  File "/usr/local/lib/python3.6/dist-packages/yacs-0.1.6-py3.6.egg/yacs/config.py", line 158, in __setattr__
    type(value), name, _VALID_TYPES
  File "/usr/local/lib/python3.6/dist-packages/yacs-0.1.6-py3.6.egg/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key QK_SCALE; valid types = {<class 'list'>, <class 'bool'>, <class 'int'>, <class 'tuple'>, <class 'str'>, <class 'float'>}

```

Did I miss something? Seems `cfg.MODEL.SWIN.QK_SCALE` can not set None.

```
python3 demo/demo.py \
    --config-file configs/coco-panoptic/maskformer_panoptic_R50_bs64_554k.yaml --video-input drive_sh.mp4 \
    --opts MODEL.WEIGHTS weights/model_final_f3fc73.pkl

```

**Comment by jinfagang** [comment]
I changed to 0.1 and it can run now

**Comment by bowenc0221** [comment]
Thanks for bringing this up, I found the PYTHON_PATH insertion place is wrong due to some auto-fix by linter. I've corrected the place in 8301efe and I do not see any config related problem on my side.

Is the problem resolved?

**Comment by jinfagang** [comment]
Yes. BTW, old question, does maskformer provides some lightweighted model? Which performance can compare with some sota methods such as SOLOv2?

**Comment by bowenc0221** [comment]
We haven't tried lightweight backbone, but since our code is based on Detectron2, you can directly use any lightweight backbones from d2go.
