### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Sunting78** [facebookresearch/MaskFormer#20]
Traceback (most recent call last):
  File "./train_net.py", line 270, in <module>
    args=(args,),
  File "/usr/local/lib64/python3.6/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "./train_net.py", line 242, in main
    cfg = setup(args)
  File "./train_net.py", line 231, in setup
    add_mask_former_config(cfg)
  File "/MaskFormer-master/mask_former/config.py", line 79, in add_mask_former_config
    cfg.MODEL.SWIN.QK_SCALE = None
  File "/usr/local/lib/python3.6/site-packages/fvcore/common/config.py", line 148, in __setattr__
    super().__setattr__(name, val)
  File "/usr/local/lib/python3.6/site-packages/yacs/config.py", line 158, in __setattr__
    type(value), name, _VALID_TYPES
  File "/usr/local/lib/python3.6/site-packages/yacs/config.py", line 525, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key QK_SCALE; valid types = {<class 'int'>, <class 'bool'>, <class 'str'>, <class 'tuple'>, <class 'float'>, <class 'list'>}

python3 ./train_net.py --config-file configs/ade20k-150/maskformer_R50_bs16_160k.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.01

**Comment by bowenc0221** [comment]
replace `SET_TO_SOME_REASONABLE_VALUE` with your value in https://github.com/facebookresearch/MaskFormer/blob/master/GETTING_STARTED.md#training--evaluation-in-command-line

**Comment by Sunting78** [comment]
> replace `SET_TO_SOME_REASONABLE_VALUE` with your value in https://github.com/facebookresearch/MaskFormer/blob/master/GETTING_STARTED.md#training--evaluation-in-command-line

I have changed value, but the peoblem may be caused by cfg.MODEL.SWIN.QK_SCALE = None?
I change cfg.MODEL.SWIN.QK_SCALE = None to cfg.MODEL.SWIN.QK_SCALE = False can work. Is it right?

**Comment by bowenc0221** [comment]
I could not reproduce your error by running your command: `python train_net.py --config-file configs/ade20k-150/maskformer_R50_bs16_160k.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.01`. Did you change anything else in the code?

**Comment by Sunting78** [comment]
> I could not reproduce your error by running your command: `python train_net.py --config-file configs/ade20k-150/maskformer_R50_bs16_160k.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.01`. Did you change anything else in the code?

Nothing changed.   
I think cfg.MODEL.SWIN.QK_SCALE = False is also right in training. It is equal to fg.MODEL.SWIN.QK_SCALE = None. Thanks.
