### ISSUE TITLE
How to prepare ground truth for MaskFormer-fixed setting?

### ISSUE THREAD

**Issue by LavenderLA** [facebookresearch/MaskFormer#22]
Thanks for your wonderful work! May I ask how to prepare classification and mask ground truth for MaskFormer-fixed training? In your paper, it says "i.e. N = K and assignment is done based on category label indices identically to per-pixel classification setup". Sorry I don't fully understand.

**Comment by bowenc0221** [comment]
In the matcher, you can simply use the category label of each `target` to index prediction. For example, given `tgt_ids = targets[b]["labels"]` where `b` is the batch index, the 0-th target is assigned to the `tgt_ids[0]`-th prediction. The corresponding index pair is `([tgt_ids[0], tgt_ids[1], tgt_ids[2], ...], [0, 1, 2, ...])`
