### ISSUE TITLE
Some questions about FLOPs

### ISSUE THREAD

**Issue by liuyang-ict** [facebookresearch/MaskFormer#28]
Hi Wencheng,
In your paper, the FLOPs of Swin-UperNet are 236, 259, 471,647 for Swin-T, Swin-S, Swin-B, Swin-L, respectively, but are different from the official FLOPs in Swin-Transformer.
Best.

**Comment by bowenc0221** [comment]
FLOPs comparison does not make any sense without specifying input sizes. We recompute all FLOPs with the same input size for a fair comparison. The FLOPs reported in the Swin Transformer paper use a different input size.

**Comment by liuyang-ict** [comment]
In the appendix of Swin-Transformer: "Swin-T, Swin-S are trained on the standard-setting as the previous approaches with an input of 512×512. Swin-B and Swin-L with z indicate that these two models are pre-trained on ImageNet-22K, and trained with the input of 640×640".
In your paper, the crop size is also 512x512. What's the difference in the input size between Swin and Maskformer.

**Comment by bowenc0221** [comment]
Yes, we train our model using the same crop size as Swin Transformer. But FLOPs calculation is separate and does not need to use the same crop size as training. We confirmed with authors of Swin Transformer and they used different input size to calculate FLOPs. Thus, we re-calculate FLOPs for a fair comparison.

**Comment by liuyang-ict** [comment]
Got it! Thanks a lot~------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月14日(星期二) 凌晨0:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/MaskFormer] Some questions about FLOPs (#28)
