### ISSUE TITLE
Calculation of PQ for semantic segmentation dataset

### ISSUE THREAD

**Issue by dingjiansw101** [facebookresearch/MaskFormer#30]
Hi, very nice work! I want to calculate the PQ for semantic segmentation dataset as shown in your paper. Which files should I modify？Or could you release the code for PQ calculation on semantic segmentation dataset?

**Comment by bowenc0221** [comment]
I have uploaded the [file to evaluate PQ for semantic segmentation](https://github.com/facebookresearch/MaskFormer/blob/main/tools/evaluate_pq_for_semantic_segmentation.py), please refer to the corresponding [README file](https://github.com/facebookresearch/MaskFormer/blob/main/tools/README.md) for its usage.

**Comment by dingjiansw101** [comment]
Thanks for sharing this.
