### ISSUE TITLE
No instruction or code for coco panoptic segmentation training?

### ISSUE THREAD

**Issue by kl2005ad** [facebookresearch/MaskFormer#35]
Looking forward to the coco panoptic instructions. Thanks!

**Comment by bowenc0221** [comment]
You can simply replace the config file [in the example](https://github.com/facebookresearch/MaskFormer/blob/main/GETTING_STARTED.md) with the the model that you want to train/evaluate. You can find corresponding config files under [MODEL_ZOO](https://github.com/facebookresearch/MaskFormer/blob/main/MODEL_ZOO.md).

**Comment by kl2005ad** [comment]
But there is no such file as register_coco_panoptic.py ? I thought dataset registration and preprocessing are necessary.

**Comment by bowenc0221** [comment]
COCO panoptic dataset is already registered in Detectron2. Please follow https://github.com/facebookresearch/detectron2/tree/main/datasets to prepare the COCO panoptic dataset.
