### ISSUE TITLE
Problem running demo on COCO Panoptic

### ISSUE THREAD

**Issue by marcomiglionico94** [facebookresearch/MaskFormer#38]
I try to run the demo.py example using the ''../configs/coco-panoptic/maskformer_panoptic_R50_bs64_554k.yaml' as configuration but i keep getting the following error: 'Non-existent config key: MODEL.RESNETS.STEM_TYPE'.
Any ideas of what can be the problem?

**Comment by AnukritiSinghh** [comment]
how did you solve this? thanks!
