### ISSUE TITLE
The pretrained model

### ISSUE THREAD

**Issue by hszyq1234** [facebookresearch/MaskFormer#4]
The pretrained models with backbone "Swin" in "COCO Panoptic Segmentation" cannot be accessed

**Comment by bowenc0221** [comment]
Can you provide the command you used and the full error message?

**Comment by hszyq1234** [comment]
I mean the pretrained models do not exist. When I try to download "https://dl.fbaipublicfiles.com/maskformer/panoptic-coco/model_final_7505c4.pkl",

**Comment by bowenc0221** [comment]
Sorry, I put the wrong link in MODEL_ZOO. The correct link should be `https://dl.fbaipublicfiles.com/maskformer/panoptic-coco/maskformer_panoptic_swin_large_IN21k_384_bs64_554k/model_final_7505c4.pkl`. Can you try it again?

I have also updated all other Swin models. Thanks for pointing this out!

**Comment by hszyq1234** [comment]
It works! Thank you!
