### ISSUE TITLE
the model becomes very bad after I set the dice_weights to 0.

### ISSUE THREAD

**Issue by SeasarStalion** [facebookresearch/MaskFormer#46]
I can train maskformer when [dice_weight=1. mask_weight=20.] or  [dice_weight=1. mask_weight=0.].
but when I set  [dice_weight=0. mask_weight=20.],the model becomes very hard to train.
How do I train this model using only focalloss?

**Comment by bowenc0221** [comment]
You might need to tune the parameter if you are not using the default setting.
