### ISSUE TITLE
How to compute the FLOPS reported in the paper

### ISSUE THREAD

**Issue by YellowPig-zp** [facebookresearch/MaskFormer#47]
Hi Bowen, thank you for such a great work! I just have a small question about how to get the reported FLOPs in the paper. Is there a script or public repo that has this functionality? Thanks!

**Comment by bowenc0221** [comment]
https://github.com/facebookresearch/detectron2/blob/main/tools/analyze_model.py

**Comment by Sunting78** [comment]
> https://github.com/facebookresearch/detectron2/blob/main/tools/analyze_model.py

Hi Bowen. I calculate the flop and params with the scirpt, but the result is not the same with your paper. 
The maskformer_swin_small_bs16_160k.yaml is 63M Params and 111G Flops. In your paper is 63M Params and 79G Flops. Is there any problems with my calculation?

python3 analyze_model.py --config-file ./configs/ade20k-150/swin/maskformer_swin_small_bs16_160k.yaml --tasks flop

[11/15 13:41:29 detectron2]: Flops table computed from only one input sample:
| module                                        | #parameters or shape   | #flops     |
|:----------------------------------------------|:-----------------------|:-----------|
| model                                         | 63.075M                | 0.111T     |
|  backbone                                     |  48.839M               |  68.021G   |
|   backbone.patch_embed                        |   4.896K               |   0.115G   |
|    backbone.patch_embed.proj                  |    4.704K              |    0.104G  |
|    backbone.patch_embed.norm                  |    0.192K              |    10.813M |
|   backbone.layers                             |   48.831M              |   67.886G  |
|    backbone.layers.0                          |    0.299M              |    6.031G  |
|    backbone.layers.1                          |    1.188M              |    5.882G  |
|    backbone.layers.2                          |    33.16M              |    49.782G |
|    backbone.layers.3.blocks                   |    14.184M             |    6.19G   |
|   backbone.norm0                              |   0.192K               |   10.813M  |
|    backbone.norm0.weight                      |    (96,)               |            |
|    backbone.norm0.bias                        |    (96,)               |            |
|   backbone.norm1                              |   0.384K               |   5.407M   |
|    backbone.norm1.weight                      |    (192,)              |            |
|    backbone.norm1.bias                        |    (192,)              |            |
|   backbone.norm2                              |   0.768K               |   2.703M   |
|    backbone.norm2.weight                      |    (384,)              |            |
|    backbone.norm2.bias                        |    (384,)              |            |
|   backbone.norm3                              |   1.536K               |   1.352M   |
|    backbone.norm3.weight                      |    (768,)              |            |
|    backbone.norm3.bias                        |    (768,)              |            |
|  sem_seg_head                                 |  14.236M               |  37.358G   |
|   sem_seg_head.pixel_decoder                  |   4.305M               |   32.395G  |
|    sem_seg_head.pixel_decoder.adapter_1       |    25.088K             |    0.582G  |
|    sem_seg_head.pixel_decoder.layer_1         |    0.59M               |    13.316G |
|    sem_seg_head.pixel_decoder.adapter_2       |    49.664K             |    0.284G  |
|    sem_seg_head.pixel_decoder.layer_2         |    0.59M               |    3.329G  |
|    sem_seg_head.pixel_decoder.adapter_3       |    98.816K             |    0.14G   |
|    sem_seg_head.pixel_decoder.layer_3         |    0.59M               |    0.832G  |
|    sem_seg_head.pixel_decoder.layer_4         |    1.77M               |    0.623G  |
|    sem_seg_head.pixel_decoder.mask_features   |    0.59M               |    13.288G |
|   sem_seg_head.predictor                      |   9.932M               |   4.955G   |
|    sem_seg_head.predictor.transformer.decoder |    9.473M              |    1.284G  |
|    sem_seg_head.predictor.query_embed         |    25.6K               |            |
|    sem_seg_head.predictor.input_proj          |    0.197M              |    69.206M |
|    sem_seg_head.predictor.class_embed         |    38.807K             |    23.194M |
|    sem_seg_head.predictor.mask_embed.layers   |    0.197M              |    0.118G  |
[11/15 13:41:29 detectron2]: Average GFlops for each type of operators:
[('conv', 32.83191595008), ('layer_norm', 0.22296760319999998), ('linear', 67.07614236672), ('matmul', 1.92566500224), ('group_norm', 0.0769406976), ('upsample_nearest2d', 0.00764854272), ('bmm', 0.139984896), ('einsum', 8.959275), ('upsample_bilinear2d', 0.29302461)]
[11/15 13:41:29 detectron2]: Total GFlops: 111.5±12.8
