### ISSUE TITLE
[Question] Corner case handling in the dataset mapper

### ISSUE THREAD

**Issue by programath** [facebookresearch/MaskFormer#48]
In `mask_former_panoptic_dataset_mapper.py`, [masks.append(pan_seg_gt == segment_info["id"]) ](https://github.com/facebookresearch/MaskFormer/blob/232bd1bc1c8929565c098c1002ebc8d21fa0f530/mask_former/data/dataset_mappers/mask_former_panoptic_dataset_mapper.py#L150) might turn out to be an empty mask since objects in the image can be removed in the previous data augmentation (e.g. crop), therefore generating an "empty gt object". I am wondering how the training will behavior in such a corner case. 
Anyone can help me answer this question?

**Comment by bowenc0221** [comment]
Training won't be affected if there is no gt.
