### ISSUE TITLE
What are cityscapes panoptic results for Maskformer?

### ISSUE THREAD

**Issue by lxtGH** [facebookresearch/MaskFormer#49]
Hi! It is a very nice work! I wonder what are cityscapes panoptic results for Maskformer?

**Comment by lxtGH** [comment]
Are there any advantages in driving scene for maskformer?

**Comment by bowenc0221** [comment]
You can find Cityscapes results here: https://github.com/facebookresearch/Mask2Former

**Comment by lxtGH** [comment]
Thanks for your reply.
