### ISSUE TITLE
semantic seg training Error

### ISSUE THREAD

**Issue by Mollylulu** [facebookresearch/MaskFormer#51]
` C = C.reshape(num_queries, -1).cpu()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

This is happened when I run with `python ./train_net.py --num-gpus 4 \
--config-file ./configs/ade20k-150/maskformer_R50_bs16_160k_my.yaml \`

hope you or anyone can help me. thanks in advance :)

**Comment by Mollylulu** [comment]
I just find that there are `151` classes in `ADE20k/annotations_detetron2`, which I use the script mentioned in `Dataset Preparation Section( `prepare_ade20k_sem_seg.py`). How to fix this prob?

**Comment by bowenc0221** [comment]
Sorry, cannot reproduce your error. The extra category is `ignore_label` which will be ignored in calculation loss.

**Comment by Mollylulu** [comment]
wired, I got it :)
