### ISSUE TITLE
Question about general inference

### ISSUE THREAD

**Issue by Trainingzy** [facebookresearch/MaskFormer#54]
Thanks for your great work!

I have two questions about general inference (Sec. 3.4). In general inference, you assign each pixel within a mask by the mask label if the (mask prediction prob * class prob) is high. 

So what the assigned class label is if the multiplied probability for some pixels within a mask is not high? If ignored, are there some pixels not assigned labels?
What if two masks have overlap pixels?

**Comment by bowenc0221** [comment]
You can refer to this implementation: https://github.com/facebookresearch/MaskFormer/blob/da3e60d85fdeedcb31476b5edd7d328826ce56cc/mask_former/mask_former_model.py#L248-L304

Argmax is used to resolve conflict: https://github.com/facebookresearch/MaskFormer/blob/da3e60d85fdeedcb31476b5edd7d328826ce56cc/mask_former/mask_former_model.py#L272

Pixels without assigned labels are set to `VOID` which is allowed in panoptic segmentation: https://github.com/facebookresearch/MaskFormer/blob/da3e60d85fdeedcb31476b5edd7d328826ce56cc/mask_former/mask_former_model.py#L262

**Comment by Trainingzy** [comment]
Cool. I got it. Thanks!
