### ISSUE TITLE
Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by xiaoquan-code** [facebookresearch/MaskFormer#58]
when I run the 'datasets/prepare_coco_stuff_10k_v1.0_sem_seg.py',  I have met this error

**Comment by bowenc0221** [comment]
https://stackoverflow.com/questions/38089950/error-opening-file-in-h5py-file-signature-not-found/43607837

**Comment by xiaoquan-code** [comment]
I have solved this error, but I met a new error.~
WARNING [01/12 14:49:26 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
sem_seg_head.pixel_decoder.adapter_1.norm.{bias, weight}
sem_seg_head.pixel_decoder.adapter_1.weight
sem_seg_head.pixel_decoder.adapter_2.norm.{bias, weight}
sem_seg_head.pixel_decoder.adapter_2.weight
sem_seg_head.pixel_decoder.adapter_3.norm.{bias, weight}
sem_seg_head.pixel_decoder.adapter_3.weight
sem_seg_head.pixel_decoder.layer_1.norm.{bias, weight}
sem_seg_head.pixel_decoder.layer_1.weight
sem_seg_head.pixel_decoder.layer_2.norm.{bias, weight}
sem_seg_head.pixel_decoder.layer_2.weight
sem_seg_head.pixel_decoder.layer_3.norm.{bias, weight}
sem_seg_head.pixel_decoder.layer_3.weight
sem_seg_head.pixel_decoder.layer_4.norm.{bias, weight}
sem_seg_head.pixel_decoder.layer_4.weight
sem_seg_head.pixel_decoder.mask_features.{bias, weight}
sem_seg_head.predictor.{bias, weight}
WARNING [01/12 14:49:26 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  stem.fc.{bias, weight}

**Comment by xiaoquan-code** [comment]
> 

I downloaded the coco-stuff-10k dataset, and I want to test on this dataset.
