### ISSUE TITLE
Question about your paper

### ISSUE THREAD

**Issue by hihunjin** [facebookresearch/MaskFormer#6]
I've read your paper. Thank you so much for such a great work.

You said you didn't do 'per-pixel classification' but I think you did 'per-pixel, per-class, binary classification'.

Is that right to understand your paper?

Thanks.

**Comment by bowenc0221** [comment]
The 'per-pixel classification' refers to classifying every pixel into one of K pre-defined category (semantic grouping) while the 'binary classification' you are referring to is differentiating foreground from background (non-semantic grouping). Yes, the binary mask prediction uses binary classification but it is not the same concept of 'classification' in the 'per-pixel classification' formulation of semantic segmentation.

I hope this explanation is clear. Please let me know if you have other question ;)

**Comment by WalBouss** [comment]
Hi,
You did such a great job!
I also have a question about the pixel decoder. 
**In section 4.1** you specify that you designed the decoder based on the popular FPN architecture. However, after the pixel decoder, you end up with C<sub> epsilon </sub> features maps of size HxW. But when you use **Swin Transformer+FPN** you should end up with feature maps of size H/4xW/4 _(assuming patch_size=4)_. 

Therefore, my question is, how _(and where in your code)_ do you upsample the feature maps to the desired size?

**Comment by bowenc0221** [comment]
Thanks, @WalBouss!

Not sure if I understand your question, but the "FPN-like" pixel decoder always upsample the features to H/4xW/4 resolution (for both ResNet and Swin Transformer). Here is the text describing this process in the paper (section 4.1):
> We repeat this process starting with the stride 32 feature map until we obtain a final feature map of stride 4.

Regarding the place to upsample feature maps to the desired size, I assume you are asking how to upsample it to the original resolution?

We generate mask at 1/4 of the original resolution, and the mask prediction is being upsampled to the original resolution with this code:
https://github.com/facebookresearch/MaskFormer/blob/2ae8543c892c5d57352fc10d55103a7254a03dad/mask_former/mask_former_model.py#L194-L199

**Comment by WalBouss** [comment]
Thank you for the clarification!
