### ISSUE TITLE
How to train instance segmentation with COCO dataset?

### ISSUE THREAD

**Issue by WuTao-CS** [facebookresearch/MaskFormer#64]
Hello, thank you for your innovative work and code.
I have seen the code for instance segmentation experiments with Maskformer in your Mask2former paper, but I can't seem to find instructions on how to use this code directly for instance segmentation training here? I wonder if you would be so kind as to update the code and config file for instance segmentation of COCO datasets using Maskformer?
Thank you!

**Comment by bowenc0221** [comment]
https://github.com/facebookresearch/Mask2Former supports MaskFormer as well.

**Comment by WuTao-CS** [comment]
Thank you for your reply, can you provide me with the corresponding config file? And in the Mask2former paper, the Maskformer with R50 as the backbone is used for instance segmentation experimental results, does it additional six encoder layers as Maskformer with R50 as the backbone did for the COCO panoptic segmentation task?

**Comment by WuTao-CS** [comment]
Hi~, I suddenly realized that I forgot to leave my email, if you can provide the config file for instance segmentation experiments with Maskformer,  my email is wutao.cs@foxmail.com. Thank you!

**Comment by rmanzanedo** [comment]
Hi @WuTao-CS ,
I am using the following config with the Mask2Fomer to run MaskFormer

_BASE_: Base-COCO-InstanceSegmentation.yaml
MODEL:
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 80
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "TransformerEncoderPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
\#    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "StandardTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "transformer_encoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    CLASS_WEIGHT: 2.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 6
    PRE_NORM: False
\#    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 0
\#    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
\#    TRAIN_NUM_POINTS: 12544
\#    OVERSAMPLE_RATIO: 3.0
\#    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
SOLVER:
  AMP:
    ENABLED: TRUE
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)

**Comment by WuTao-CS** [comment]
Hi @rmanzanedo ，thanks for your help！

**Comment by satpalsr** [comment]
Hey @WuTao-CS, Did you successfully trained it for image segmentation. What was your experience?
