### ISSUE TITLE
About the missing file.

### ISSUE THREAD

**Issue by HCShi** [facebookresearch/MaskFormer#7]
Hello, I have not found the file 'prepare_ade20k_panoptic_annotations.py' to generate the ade20k panoptic annotations, could you please provide the file? By the way, if the MaskFormer could be used on Mapillary Vistas panoptic segmentation?
Looking forward to your reply.

**Comment by bowenc0221** [comment]
Dataset preparation scripts are under `datasets`. You can run `python datasets/prepare_ade20k_pan_seg.py` to generate ADE20K panoptic segmentation.

MaskFormer can be used on Mapillary Vistas panoptic segmentation, but you will need to define a custom dataset for loading Mapillary Vistas panoptic annotations.

**Comment by HCShi** [comment]
> Dataset preparation scripts are under `datasets`. You can run `python datasets/prepare_ade20k_pan_seg.py` to generate ADE20K panoptic segmentation.
> 
> MaskFormer can be used on Mapillary Vistas panoptic segmentation, but you will need to define a custom dataset for loading Mapillary Vistas panoptic annotations.

Thanks for your reply. I found that the prepare_ade20k_pan_seg.py needs 'tools/ade20k_instance_imgCatIds.json' and 'tools/ade20k_instance_catid_mapping.txt', but I could not find them in tools directory, could you please provide the files?

**Comment by YJHMITWEB** [comment]
Same here, please.

**Comment by bowenc0221** [comment]
Sorry about the inconvenient, I have uploaded the missing files, please try again.

**Comment by HCShi** [comment]
> Sorry about the inconvenience, I have uploaded the missing files, please try again.

Thanks a lot!
