### ISSUE TITLE
Support for custom dataset

### ISSUE THREAD

**Issue by FrancescoMandru** [facebookresearch/MaskFormer#8]
Hi, thank tou for sharing your code, I just have 2 questions.

1) How should I prepare my custom dataset to test the model?
2) Do you know the maximum resolution achievable by this model to obtain good results? I mean, does this model work with 1024x1024 images for example?

Thank you!

**Comment by bowenc0221** [comment]
You can refer to [this document](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html) for defining a custom dataset.

The maximum resolution depends on your GPU memory, I'm able to train Mapillary Vistas with 1280x 1280 images.

**Comment by FrancescoMandru** [comment]
@bowenc0221 Thank you. Actually I'm a bit confused, bacuse you provide a link for preparing dataset for Detectron 2. And in this repository you provide to the network different datasets with different structures, so which is the structure to follow? I mean, if I have a dataset of images and I want to use your network how should I prepare my annotations? Can I copy from one of the different dataset configuration that you provide?

**Comment by bowenc0221** [comment]
There is no "standard" dataset structure, you only need to register your own dataset under `DatasetCatalog` by providing the `gt_root` and `image_root`. So you should not place your own dataset into any of those structure, instead, you only need to separate train and val data into different folders and follow examples either in the [document](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html) or [my code](https://github.com/facebookresearch/MaskFormer/tree/master/mask_former/data/datasets) to register your dataset.
