### ISSUE TITLE
Panoptic segmentation on Cityscapes

### ISSUE THREAD

**Issue by Ratriswat** [facebookresearch/MaskFormer#9]
Thanks for your excellent work.

May I know if you have tried to do panoptic segmentation on Cityscapes dataset? 

I am trying to do it but got weird results.  I prepared the cityscapes dataset by following the instructions and modified the config files from the semantic config file "maskformer_R101_bs16_90k.yaml".

If you have tried, could you please provide the config files for panoptic segmentation on Cityscapes?

Thank you.

**Comment by bowenc0221** [comment]
I have not tried to train MaskFormer for panoptic segmentation on the Cityscapes dataset. You could refer to the [Panoptic-DeepLab](https://github.com/facebookresearch/detectron2/tree/master/projects/Panoptic-DeepLab) project to check your setting.

**Comment by Ratriswat** [comment]
> I have not tried to train MaskFormer for panoptic segmentation on the Cityscapes dataset. You could refer to the [Panoptic-DeepLab](https://github.com/facebookresearch/detectron2/tree/master/projects/Panoptic-DeepLab) project to check your setting.

Ok, thanks.

**Comment by EnternalTwinkle** [comment]
I am trying to do panoptic segmentation on Cityscapes dataset, too. It seems that the quality of the mask is not good. I would like to ask you how it is going。

**Comment by timmh** [comment]
I am also training on Cityscapes based on [maskformer_R101c_bs16_90k.yaml](https://github.com/facebookresearch/MaskFormer/blob/335d7783d2c6c5fcf248fe28acd7d5e4abd210bc/configs/cityscapes-19/maskformer_R101c_bs16_90k.yaml) and seeing pretty good segmentation results, but bad instance discrimination. Does anybody have an idea on how to improve this?

**Comment by EnternalTwinkle** [comment]
> I am also training on Cityscapes based on [maskformer_R101c_bs16_90k.yaml](https://github.com/facebookresearch/MaskFormer/blob/335d7783d2c6c5fcf248fe28acd7d5e4abd210bc/configs/cityscapes-19/maskformer_R101c_bs16_90k.yaml) and seeing pretty good segmentation results, but bad instance discrimination. Does anybody have an idea on how to improve this?

I also encountered the same problem as you. Below is my result on the validation set (R50).
|        |   PQ   |   SQ   |   RQ   |  #categories  |
|:------:|:------:|:------:|:------:|:-------------:|
|  All   | 51.054 | 79.138 | 62.693 |      19       |
| Things | 35.964 | 77.396 | 45.576 |       8       |
| stuff  | 62.029 | 80.405 | 75.142 |      11       |

--------------------------------
Score Average : 0.757    0.530
--------------------------------

##################################################
what           :             AP         AP_50%
##################################################
person         :          0.050          0.147
rider          :          0.075          0.219
car            :          0.221          0.419
truck          :          0.153          0.212
bus            :          0.371          0.497
train          :          0.286          0.522
motorcycle     :          0.061          0.213
bicycle        :          0.038          0.138
--------------------------------------------------
average        :          0.157          0.296

**Comment by bowenc0221** [comment]
You can find Cityscapes results here: https://github.com/facebookresearch/Mask2Former
